version: '2'

services:
  ui:
    image: google/nodejs
    container_name: monitor-d-frontend
    volumes:
      - ./web:/app/
    working_dir: /app/
    command: npm start
    ports:
      - "8080:8080"

  coreapi:
    image: java:8-jdk-alpine
    container_name: monitor-d-core-api
    volumes:
      - ./microservices/core-api/target/:/app/
    working_dir: /app/
    command: java -jar  -Dspring.profiles.active=integration   /app/mond-core-1.0.0-SNAPSHOT.jar
    ports:
      - "8181:8181"
    links:
      - database
  database:
    image: mongo
    container_name: monitor-d-database
    volumes:
      - /data/db
    ports:
      - "27017:27017"
