---
# tasks file for spark
# After installed go to http://hadoopmaster:4040/jobs/ to see the jobs executed
# Need to configure hive to
- name: stat /tmp/spark-1.6.1-bin-hadoop2.6.tgz
  stat: path=/tmp/spark-1.6.1-bin-hadoop2.6.tgz
  register: sparkbinary_stat
# - name: stat /usr/local/spark
#   stat: path=/usr/local/hive
#   register: hive_dir_stat

- name: uncompress spark tarball and place in /usr/local/
  unarchive: src=spark-1.6.1-bin-hadoop2.6.tgz dest=/usr/local/ owner=hadoop group=hadoop

- name: rename file
  command: creates="/usr/local/spark" mv /usr/local/spark-1.6.1-bin-hadoop2.6/  /usr/local/spark
