---
# tasks file for env
# TODO: Additional Things to install 'mysql-server' for hive metastore.
# TODO: CREATE PLAYBOOK ROLE FOR GANGLIA
# yum install http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.rpm



- name: install git, java7
  yum: name={{ item }} state=latest
  with_items:
    - java-1.7.0-openjdk-devel.x86_64
  tags:
    - provision_rpm
# Ssh performance and disabling of knownkeys

- name: setup hosts file
  template: src=hosts.j2   dest=/etc/hosts
  register: installing_hosts_config

- name: setup bashrc file
  template: src=bashrc.j2  dest={{ HOME }}/.bashrc
  register: installing_hosts_config
