---
###################################################################################
# Author: Zak Hassan
# Description: Playbook Apache Kafka on openstack like less than 1 min. :)
#
###################################################################################
# Creating kafka user
- group: name=kafka state=present
- user: name=kafka comment="kafka" group=kafka shell=/bin/bash
- name: stat /tmp/{{ kafka_binary }}
  stat: path=/tmp/{{ kafka_binary }}
  register: kfbinary_stat
- name: copy kafka to tmp folder
  copy: src={{ kafka_binary }} dest=/tmp/ group=kafka
  when: kfbinary_stat.stat.exists == False
  tags:
     - provision_copy_to_remote
- name: unzip tarball and place in /usr/local/
  command: tar zxvf /tmp/{{ kafka_binary }}  -C /usr/local/
  tags:
    - Provision_Unzip_Move_To_User_Local
- name: stat {{ kafka_install_dir }}
  stat: path={{ kafka_install_dir }}
  register: kf_dir_stat
- name: rename file
  command: creates="{{ kafka_install_dir }}" mv /usr/local/{{ kafka_version }}/  {{ kafka_install_dir }}
  when: kf_dir_stat.stat.exists == False
- name: change permissions to kafka user for {{ kafka_version }}
  command: chown -R kafka:kafka {{ kafka_install_dir }}
- name: setup kafka property file
  template: src=server.properties.j2 dest=/usr/local/kafka/config/server.properties
- name: setup systemd unit file
  template: src=kafka.systemd.j2 dest=/lib/systemd/system/kafka.service
  register: install_config
  notify: reload systemd
- name: enable kafka
  sudo: yes
  service: name=kafka enabled=yes state=started
