spring:
    profiles: dev
server:
    port: 8181

---

spring:
    profiles: integration
#    data.mongodb.uri: mongodb://localhost:27017/mydb
server:
    port: 8181         # Note: Change ip below to the correct mongodb ip address.

#  spring:
#    profiles: integration
# use local or embedded mongodb at localhost:27017
#  server:
#    port: 8080
#
#  spring:
#    profiles: production
#  spring:
#    data.mongodb.uri: mongodb://<user>:<passwd>@<url>:<port>/<dbname>
#  server:
#    port: 8181
