spring:
    profiles: dev
server:
    port: 8080

---

spring:
    profiles: integration
server:
    port: 8181         # Note: Change ip below to the correct mongodb ip address.
    data.mongodb.uri: mongodb://192.168.99.100:27017/mydb

#  spring:
#    profiles: integration
# use local or embedded mongodb at localhost:27017
#  server:
#    port: 8080
#
#  spring:
#    profiles: production
#  spring:
#    data.mongodb.uri: mongodb://<user>:<passwd>@<url>:<port>/<dbname>
#  server:
#    port: 8181
