---
# tasks file for elasticsearch
#https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.3/elasticsearch-2.3.3.tar.gz

- name: stat /tmp/elasticsearch-2.3.3.tar.gz
  stat: path=/tmp/elasticsearch-2.3.3.tar.gz
  register: elastic_binary_stat

- name: Downloading Apache Pig
  get_url: url=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.3/elasticsearch-2.3.3.tar.gz  dest=/tmp/elasticsearch-2.3.3.tar.gz
  when: elastic_binary_stat.stat.exists == False

- name: rename file
  command: chown hadoop:hadoop /tmp/elasticsearch-2.3.3.tar.gz


- name: uncompress pig tarball and place in /usr/local/
  unarchive: src=/tmp/elasticsearch-2.3.3.tar.gz dest=/usr/local/ owner=hadoop group=hadoop

- name: rename file
  command: creates="/usr/local/elasticsearch" mv /usr/local/elasticsearch-2.3.3  /usr/local/elasticsearch
