---
# tasks file for oozie
###################################################################################
#
# Author: Zak Hassan
# Description: Playbook Apache Zookeeper on Openstack like less than 1 min. :)
#
###################################################################################

- name: download zookeeper from apache mirror
  command: wget http://apache.mirror.vexxhost.com/oozie/4.2.0/oozie-4.2.0.tar.gz -P /tmp/
  when: download_oozie is defined

# Creating zookeeper user
- group: name=oozie state=present

- user: name=oozie comment="oozie" group=oozie shell=/bin/bash

- name: stat /tmp/oozie-distro-4.2.0.zip
  stat: path=/tmp/oozie-distro-4.2.0.zip
  register: ooziebinary_stat

- name: copy zookeeper to tmp folder
  copy: src=oozie-distro-4.2.0.zip dest=/tmp/
  when: ooziebinary_stat.stat.exists == False
  tags:
    - provision_copy_to_remote

- name: unzip tarball and place in /usr/local/
  unarchive: src=/tmp/oozie-distro-4.2.0.zip dest=/usr/local/ copy=no

- name: rename file
  command: creates="/usr/local/oozie" mv /usr/local/oozie-4.2.0  /usr/local/oozie

- name: setup oozie-site.xml file
  template: src=oozie-site.xml.j2 dest=/usr/local/oozie/conf/oozie-site.xml

# TODO: Need to create systemd file once installation confirmed
# - name: setup systemd unit file
#   template: src=oozie.service.j2 dest=/lib/systemd/system/oozie.service
#   notify: reload systemd
# - name: enable oozie
#   sudo: yes
#   service: name=oozie enabled=yes state=started
